### ISSUE TITLE
Getting a crash on click of Begin verifying button in Flutter sdk (Android).

### ISSUE THREAD

**Issue by ravi-83** [jorgefspereira/persona_flutter#13]
Logs---

E/AndroidRuntime( 3518): FATAL EXCEPTION: main
E/AndroidRuntime( 3518): Process: com.tripeers.ziffiy, PID: 3518
E/AndroidRuntime( 3518): com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.errors[0].details
E/AndroidRuntime( 3518): 	at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:172)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:69)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/AndroidRuntime( 3518): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponse_ErrorJsonAdapter.fromJson(UiTransitionErrorResponse_ErrorJsonAdapter.kt:43)
E/AndroidRuntime( 3518): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponse_ErrorJsonAdapter.fromJson(UiTransitionErrorResponse_ErrorJsonAdapter.kt:21)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/AndroidRuntime( 3518): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponseJsonAdapter.fromJson(UiTransitionErrorResponseJsonAdapter.kt:38)
E/AndroidRuntime( 3518): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponseJsonAdapter.fromJson(UiTransitionErrorResponseJsonAdapter.kt:21)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/AndroidRuntime( 3518): 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:58)
E/AndroidRuntime( 3518): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionWorker$run$1.invokeSuspend(UiTransitionWorker.kt:32)
E/AndroidRuntime( 3518): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 3518): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime( 3518): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3518): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3518): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime( 3518): 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E/AndroidRuntime( 3518): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3518): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 3518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process ( 3518): Sending signal. PID: 3518 SIG: 9

**Comment by srcnysf** [comment]
Same here @jorgefspereira I saw the last commit on master and it seems we will need more null checks :( 

```FATAL EXCEPTION: main
E[/AndroidRuntime]()(19700): Process: com.swanbitcoin.android, PID: 19700
E[/AndroidRuntime]()(19700): com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.errors[0].details
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:172)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:69)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E[/AndroidRuntime]()(19700): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponse_ErrorJsonAdapter.fromJson(UiTransitionErrorResponse_ErrorJsonAdapter.kt:43)
E[/AndroidRuntime]()(19700): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponse_ErrorJsonAdapter.fromJson(UiTransitionErrorResponse_ErrorJsonAdapter.kt:21)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E[/AndroidRuntime]()(19700): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponseJsonAdapter.fromJson(UiTransitionErrorResponseJsonAdapter.kt:38)
E[/AndroidRuntime]()(19700): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionErrorResponseJsonAdapter.fromJson(UiTransitionErrorResponseJsonAdapter.kt:21)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E[/AndroidRuntime]()(19700): 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:58)
E[/AndroidRuntime]()(19700): 	at com.withpersona.sdk.inquiry.ui.network.UiTransitionWorker$run$1.invokeSuspend(UiTransitionWorker.kt:32)
E[/AndroidRuntime]()(19700): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E[/AndroidRuntime]()(19700): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E[/AndroidRuntime]()(19700): 	at android.os.Handler.handleCallback(Handler.java:938)
E[/AndroidRuntime]()(19700): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E[/AndroidRuntime]()(19700): 	at android.os.Looper.loopOnce(Looper.java:201)
E[/AndroidRuntime]()(19700): 	at android.os.Looper.loop(Looper.java:288)
E[/AndroidRuntime]()(19700): 	at android.app.ActivityThread.main(ActivityThread.java:7838)
E[/AndroidRuntime]()(19700): 	at java.lang.reflect.Method.invoke(Native Method)
E[/AndroidRuntime]()(19700): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E[/AndroidRuntime]()(19700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I[/Process]() (19700): Sending signal. PID: 19700 SIG: 9
Lost connection to device.```

**Comment by jorgefspereira** [comment]
Hi @srcnysf. This seems to be an internal error with a dependency of the Persona Android SDK itself, and not related to the this flutter wrapper. Try to report the error on the Persona issue tracker to see if they can fix it.
