### ISSUE TITLE
persona_widget.dart:26:3: Unexpected text 'late'.

### ISSUE THREAD

**Issue by timfong888** [jorgefspereira/persona_flutter#17]
I just ran the code with the following:

` flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs`

The 'late' modifier seems to be standard and is here, same as in the install code:

`   late InquiryConfiguration _configuration;`

But in my editor and when running the build_runner locally I get this error with 'late'.

So I am puzzled and stuck

**Comment by jorgefspereira** [comment]
Hi @timfong888,

Seems you are using an old version of Dart, since 'late' modifier was introduced only in Dart 2.12. Try to upgrade you minimum Dart sdk version on your pubspec.yaml to 2.12.0 and see if fixes the issue.
