### ISSUE TITLE
remove 'late' and compiled Flutter/Dart app successfully but "start inquiry" button generates errors

### ISSUE THREAD

**Issue by timfong888** [jorgefspereira/persona_flutter#18]
I get the following error when running in the ios Simulator:

`flutter: - Inquiry Template Ids with prefix: itmpl are not supported in this version, please upgrade to an SDK version >= 2.0.0.`

I don't think that's referring to the dart version: `dart-lang/dart/dart: stable 2.16.2, HEAD`

So I am assuming it's requiring that I need to use persona SDK v 2.0

However, I'm using the pub.dev package, which I assume would be using the correct SDK.

Based on the instructions, I am unclear what else I need to do to get it to work.

Note: I am creating the Flutter mobile app using FlutterFlow.

**Comment by jorgefspereira** [comment]
Hi @timfong888 

Check the plugin prerelease version [3.0.0-beta.0](https://pub.dev/packages/persona_flutter/versions/3.0.0-beta.0).

The new inquiry templates format (itmpl) are only supported on the Persona SDK 2.0 and above. The Prerelease version implements the newer SDK version.

**Comment by timfong888** [comment]
When I set the dependency to beta I get an error. Do you have a cloneable sample that works with the v2 SDK?  That I can clone and run locally?

**Comment by jorgefspereira** [comment]
Yes. Clone the repository and run the folder example. Its a test project for the plugin.
