### ISSUE TITLE
MissingPluginException(No implementation found for method 

### ISSUE THREAD

**Issue by timfong888** [jorgefspereira/persona_flutter#19]
Hi, I get the following error after a 'flutter run'.  I basically created a working flutter project using the command line and then updated main.dart to what you have in the example/lib.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(39)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel persona_flutter)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>

The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:62415/sGsJRbl3Ces=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(39)] Unhandled Exception: MissingPluginException(No implementation found for method start on channel persona_flutter)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
```

I ran under different `flutter channel` and got furthest by setting to `beta`.

I checked in the dependencies .pub_cache for what is being used:

```
@override
  Future<void> init({required InquiryConfiguration configuration}) async {
    return _channel.invokeMethod('init', configuration.toJson());
  }

  @override
  Future<void> start() async {
    return _channel.invokeMethod('start');
  }
```

**Comment by jorgefspereira** [comment]
Hi @timfong888, can you paste the output of the command “flutter doctor”? What platform are you targeting? iOS?

**Comment by timfong888** [comment]
> Hi @timfong888, can you paste the output of the command “flutter doctor”? What platform are you targeting? iOS? 

Yes I am redoing everything but it was fine with flutter doctor for iOS.

**Comment by jorgefspereira** [comment]
Hi @timfong888, I ran here a new flutter create project with dependency `persona_flutter: ^3.0.0-beta.0` and everything worked. Here is my flutter doctor output for comparison.

[✓] Flutter (Channel beta, 3.1.0-9.0.pre, on macOS 12.4 21F79 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.69.0)
