### ISSUE TITLE
Feature Request: Pass Fields

### ISSUE THREAD

**Issue by tuanvugoodmoney** [jorgefspereira/persona_flutter#2]
Persona is also able to accept Fields. See [Android](https://sdk.withpersona.com/android/docs/index.html) & [IOS](https://sdk.withpersona.com/ios/docs/Structs/Fields.html) documentation.

Add ability to pass along Fields to Persona.

**Comment by jorgefspereira** [comment]
I'll update the plugin to the most recent SDK version and add the ability to pass the Fields structure.

**Comment by jorgefspereira** [comment]
Released version 1.1.0 with support for Fields. Thanks
