### ISSUE TITLE
merge fails on git pull origin v2

### ISSUE THREAD

**Issue by timfong888** [jorgefspereira/persona_flutter#20]
I cloned, switched branch to 'v2' and did a git pull after setting config pull.rebase to false.

I get these errors which was a little tricky to go in and clean, so wanted to check in first:

timfong@Tims-MacBook-Pro persona_flutter % git pull origin v2
From github.com:jorgefspereira/persona_flutter
 * branch            v2         -> FETCH_HEAD
Auto-merging pubspec.yaml
CONFLICT (content): Merge conflict in pubspec.yaml
Removing lib/src/types/verifications.dart
Removing lib/src/types/typedefs.dart
Removing lib/src/types/relationships.dart
Auto-merging lib/src/types/inquiry.dart
CONFLICT (content): Merge conflict in lib/src/types/inquiry.dart
CONFLICT (modify/delete): lib/src/types/fields.dart deleted in 9f48fbd924ecdfa76d945677fb1a5f5d359c9b57 and modified in HEAD. Version HEAD of lib/src/types/fields.dart left in tree.
CONFLICT (modify/delete): lib/src/types/attributes.dart deleted in 9f48fbd924ecdfa76d945677fb1a5f5d359c9b57 and modified in HEAD. Version HEAD of lib/src/types/attributes.dart left in tree.
Auto-merging lib/src/platform/persona_platform_interface.dart
CONFLICT (content): Merge conflict in lib/src/platform/persona_platform_interface.dart
Auto-merging lib/src/platform/persona_method_channel.dart
CONFLICT (content): Merge conflict in lib/src/platform/persona_method_channel.dart
Auto-merging lib/persona_flutter.dart
Auto-merging ios/persona_flutter.podspec
CONFLICT (content): Merge conflict in ios/persona_flutter.podspec
Auto-merging ios/Classes/SwiftPersonaFlutterPlugin.swift
Auto-merging example/android/app/src/main/AndroidManifest.xml
Auto-merging example/android/app/build.gradle
Auto-merging android/src/main/kotlin/com/jorgefspereira/persona_flutter/PersonaFlutterPlugin.kt
CONFLICT (content): Merge conflict in android/src/main/kotlin/com/jorgefspereira/persona_flutter/PersonaFlutterPlugin.kt
Auto-merging android/build.gradle
CONFLICT (content): Merge conflict in android/build.gradle
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Auto-merging CHANGELOG.md
CONFLICT (content): Merge conflict in CHANGELOG.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by timfong888** [comment]
I am unable to 'flutter run' the example code.  

Here is my flutter doctor:

[✓] Flutter (Channel beta, 3.1.0-9.0.pre, on macOS 12.4 21F79 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

There are a ton of errors so I am guessing something about the environment needs to be sorted first?

**Comment by timfong888** [comment]
I did a fork and downloaded locally....git pull to get the v2 (sdk v2 for personna) always has merge conflicts, which seems a little funny because I have to manually go into each file to correct it after doing git pull, even with rebase.  Thoughts on this, this is unexpected when all I am doing is changing branches.

**Comment by jorgefspereira** [comment]
Hi @timfong888, I've tested here and I got the merge conflicts you described. This worked for me:

1 - I've deleted the repository and cloned again (fresh start). 
2 - Used `git checkout v2` to pull the v2 branch.

Actually the v2 branch should have their own git repository...but for easier maintenance I kept both versions here :)
