### ISSUE TITLE
Retrieve an account

### ISSUE THREAD

**Issue by loic-hamdi** [jorgefspereira/persona_flutter#26]
Hey,

I don't see in the documentation a way to retrieve an account like [https://docs.withpersona.com/reference/apiv1accountsaccount-id-1](https://docs.withpersona.com/reference/apiv1accountsaccount-id-1)
Is it something that you plan to implement?

**Comment by jorgefspereira** [comment]
Hi @loic-hamdi. Retrieving an account seems to be an API feature and not something that's included in the native SDKs. The purpose of this plugin is to provide a better flutter integration for the native SDKs only.
