### ISSUE TITLE
Error Android when compile :app:mergeExtDexDebug

### ISSUE THREAD

**Issue by RicharC293** [jorgefspereira/persona_flutter#37]
With this gradle:

 ./gradlew --version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (JetBrains s.r.o. 17.0.6+0-17.0.6b829.9-10027231)
OS:           Mac OS X 14.1.1 aarch64

Flutter doctor -v
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.1.1 23B81 darwin-arm64, locale es-419)
    • Flutter version 3.13.5 on channel stable at /Users/richarcangui/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (3 months ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/richarcangui/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • LM X525 (mobile)          • LMX525USUKZP5D9PE6                   • android-arm    • Android 10 (API 29)
    • iPhone de Richar (mobile) • 00008120-00044C500C00C01E            • ios            • iOS 17.1.2 21B101
    • iPhone 15 Pro (mobile)    • 4084559E-4A21-450A-A93B-60D7184A85BF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

Show me this error when compile, maybe have any idea to solve this issue?
  persona_flutter: ^3.1.2

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform inquiry-internal-2.10.6.aar (com.withpersona.sdk2:inquiry-internal:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/98b0af604352965770b1ba6c8537699e/transformed/jetified-inquiry-internal-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform dynamic-feature-2.10.6.aar (com.withpersona.sdk2:dynamic-feature:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/82fe16d367aef41784b3cbe2d1d0f83d/transformed/jetified-dynamic-feature-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform ui-2.10.6.aar (com.withpersona.sdk2:ui:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/8212f7a71a29d7639d8aba021cbe7302/transformed/jetified-ui-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform government-id-2.10.6.aar (com.withpersona.sdk2:government-id:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/5d23a90d142b1ca1837fe4dc4372dfbb/transformed/jetified-government-id-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform selfie-2.10.6.aar (com.withpersona.sdk2:selfie:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/5153765995fc6e74a00184039a7ac557/transformed/jetified-selfie-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform document-2.10.6.aar (com.withpersona.sdk2:document:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/24b2dceb5b7676a752ef410a004239fc/transformed/jetified-document-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform permissions-2.10.6.aar (com.withpersona.sdk2:permissions:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/7336ce77c6ac4fbfe5be27daecf2e53e/transformed/jetified-permissions-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform modal-2.10.6.aar (com.withpersona.sdk2:modal:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/56a726dd3942350672ea95568b73816b/transformed/jetified-modal-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform nfc-2.10.6.aar (com.withpersona.sdk2:nfc:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/e12c6f0dbabf0ad0d11b384888574337/transformed/jetified-nfc-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform ui-step-renderer-2.10.6.aar (com.withpersona.sdk2:ui-step-renderer:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/a48208b2cded583fde87a1ea9c4a4654/transformed/jetified-ui-step-renderer-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform network-2.10.6.aar (com.withpersona.sdk2:network:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/18324e65a2c8f1fbfd391ef6e9cdcf96/transformed/jetified-network-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform camera-2.10.6.aar (com.withpersona.sdk2:camera:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/fac8b9b89802459e7202da8996d90f15/transformed/jetified-camera-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform inquiry-types-2.10.6.aar (com.withpersona.sdk2:inquiry-types:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/8658381712aa7b71c2f8cd226fd2797b/transformed/jetified-inquiry-types-2.10.6-runtime.jar.
         > Error while dexing.
   > Failed to transform launchers-2.10.6.aar (com.withpersona.sdk2:launchers:2.10.6) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/richarcangui/.gradle/caches/transforms-3/68fb5a84f1e77909edbd428696496977/transformed/jetified-launchers-2.10.6-runtime.jar.
         > Error while dexing.

**Comment by JoelOvien** [comment]
Looks like some one was able to resolve this here

https://github.com/jorgefspereira/persona_flutter/issues/33
