### ISSUE TITLE
New Feature: additionalFields in Fields

### ISSUE THREAD

**Issue by tuanvugoodmoney** [jorgefspereira/persona_flutter#4]
There is a variable called additionalFields that can also be passed into Fields. This would be a good place to put passthrough client information to Persona. https://sdk.withpersona.com/ios/docs/Structs/Fields.html#/s:7Persona6FieldsV010additionalB0SDySSAA12InquiryFieldOGSgvp.

**Comment by jorgefspereira** [comment]
hi @tuanvugoodmoney I'll add this feature in the next release
