### ISSUE TITLE
Sealed classes are not supported as program classes

### ISSUE THREAD

**Issue by sajanIocod** [jorgefspereira/persona_flutter#40]
Launching lib/main.dart on SM A156E in debug mode...
ERROR:/Users/anagha/.gradle/caches/transforms-3/6ac00f98d3e793ca12fe3dc3a2ef8e09/transformed/jetified-dynamic-feature-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/cedccb49f1bd865ab12562cd35ad15b1/transformed/jetified-launchers-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/782e743035d301c89359ce1254fa12f2/transformed/jetified-ui-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/9a9dfe0db5b70a364769d483eeee7f03/transformed/jetified-document-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/c5f488df0f765e3c2abe8f0d4ebf3bd7/transformed/jetified-selfie-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/4802f9227a0333f8852345f024cfea47/transformed/jetified-inquiry-internal-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/99862fa9e77bbc7c82eb89091beb9513/transformed/jetified-inquiry-types-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/10c3383e37c64b7a9cc62e07d2c62b2c/transformed/jetified-permissions-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/60248ce333ae0dfd738f1916034dcec1/transformed/jetified-government-id-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/62123798dd48ed78fe27728eb4b609e4/transformed/jetified-modal-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/45b22c70f4e8475fa1c3056b6b8607e9/transformed/jetified-nfc-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/ee8c0066f552f38e2c9ae98604748c11/transformed/jetified-webrtc-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/e579dc7a21f00057a16473e634a32eee/transformed/jetified-ui-step-renderer-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/5d7e548a0e83e216c41c0517b1e66a5e/transformed/jetified-camera-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
ERROR:/Users/anagha/.gradle/caches/transforms-3/784534c9839bfde1fa90bbb2c2337caa/transformed/jetified-network-2.10.9-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform inquiry-internal-2.10.9.aar (com.withpersona.sdk2:inquiry-internal:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/4802f9227a0333f8852345f024cfea47/transformed/jetified-inquiry-internal-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform dynamic-feature-2.10.9.aar (com.withpersona.sdk2:dynamic-feature:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/6ac00f98d3e793ca12fe3dc3a2ef8e09/transformed/jetified-dynamic-feature-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform ui-2.10.9.aar (com.withpersona.sdk2:ui:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/782e743035d301c89359ce1254fa12f2/transformed/jetified-ui-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform government-id-2.10.9.aar (com.withpersona.sdk2:government-id:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/60248ce333ae0dfd738f1916034dcec1/transformed/jetified-government-id-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform selfie-2.10.9.aar (com.withpersona.sdk2:selfie:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/c5f488df0f765e3c2abe8f0d4ebf3bd7/transformed/jetified-selfie-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform document-2.10.9.aar (com.withpersona.sdk2:document:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/9a9dfe0db5b70a364769d483eeee7f03/transformed/jetified-document-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform permissions-2.10.9.aar (com.withpersona.sdk2:permissions:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/10c3383e37c64b7a9cc62e07d2c62b2c/transformed/jetified-permissions-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform modal-2.10.9.aar (com.withpersona.sdk2:modal:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/62123798dd48ed78fe27728eb4b609e4/transformed/jetified-modal-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform nfc-2.10.9.aar (com.withpersona.sdk2:nfc:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/45b22c70f4e8475fa1c3056b6b8607e9/transformed/jetified-nfc-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform ui-step-renderer-2.10.9.aar (com.withpersona.sdk2:ui-step-renderer:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/e579dc7a21f00057a16473e634a32eee/transformed/jetified-ui-step-renderer-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform camera-2.10.9.aar (com.withpersona.sdk2:camera:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/5d7e548a0e83e216c41c0517b1e66a5e/transformed/jetified-camera-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform webrtc-2.10.9.aar (com.withpersona.sdk2:webrtc:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/ee8c0066f552f38e2c9ae98604748c11/transformed/jetified-webrtc-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform network-2.10.9.aar (com.withpersona.sdk2:network:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/784534c9839bfde1fa90bbb2c2337caa/transformed/jetified-network-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform inquiry-types-2.10.9.aar (com.withpersona.sdk2:inquiry-types:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/99862fa9e77bbc7c82eb89091beb9513/transformed/jetified-inquiry-types-2.10.9-runtime.jar.
         > Error while dexing.
   > Failed to transform launchers-2.10.9.aar (com.withpersona.sdk2:launchers:2.10.9) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/anagha/.gradle/caches/transforms-3/cedccb49f1bd865ab12562cd35ad15b1/transformed/jetified-launchers-2.10.9-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
Exited (1)

**Comment by bazl-E** [comment]
FIX :

**Replace your _settings.gradle_ with the following :**
```
/ Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

```

**Comment/Remove the following lines from  _android/app/build.gradle_**

```
 plugins {
     id "com.android.application"
     id "kotlin-android"
     id "dev.flutter.flutter-gradle-plugin"
 }
```
**Replace the following lines in the same file**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}
```
**with this**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}
def flutterRoot = localProperties.getProperty('flutter.sdk')
```

**Add the following before the android{ tag in same file**
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
```
**Update the ext.kotlin_version  to(android/build.gradle)** 
`ext.kotlin_version = '1.9.0'`
**Also add the following to android/build.gradle file**
```
dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

Hope it helps
