### ISSUE TITLE
dart sdk version downgrade

### ISSUE THREAD

**Issue by legendar** [jorgefspereira/persona_flutter#49]
in the latest release required dart sdk version is changed to >= 3.4.4 is it required change or can it be downgraded to >=3.4.0?

I'm asking because flutterflow uses 3.4.3 in web builder which leads to the following error:

```
Resolving dependencies...
The current Dart SDK version is 3.4.3.

Because wemates depends on persona_flutter &gt;=3.2.3 which requires SDK version &gt;=3.4.4 &lt;4.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.22.3. 

```

**Comment by jorgefspereira** [comment]
Oh i didn't known about that restriction. I'll change it to >= 3.4.0
