### ISSUE TITLE
null-safety

### ISSUE THREAD

**Issue by higorlapacw** [jorgefspereira/persona_flutter#5]
Do you have any plans to support null-safety?

**Comment by jorgefspereira** [comment]
@higorlapacw yes, new version with null-safety will be released very soon.

**Comment by higorlapacw** [comment]
Thanks, @jorgefspereira!

**Comment by tuanvugoodmoney** [comment]
@jorgefspereira Hi Jorge, let me know if you'd like help on this. We need it for our app and I can maybe get a PR out by tomorrow if you'd like. Thanks

**Comment by jorgefspereira** [comment]
Hi @tuanvugoodmoney, no need...I'll be pushing a null safety version of the plugin this week 👊

**Comment by jorgefspereira** [comment]
Hi @tuanvugoodmoney, I just publish the plugin version 2.0.0 with null-safety support. Feel free to report or PR any issue 😄

**Comment by tuanvugoodmoney** [comment]
@jorgefspereira You rock
